
# 指定flyway脚本位置
spring.flyway.locations: classpath:/db/migration
# 打开flyway执行日志
logging.level.org.flywaydb: debug

#spring.profiles.include: dev
server:
  port: 8800




spring.datasource.url: jdbc:mysql://127.0.0.1:3306/tttttt?characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: admin
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#jooq name
generator.database.name: org.jooq.meta.mysql.MySQLDatabase

# spring cloud
spring.application.name: exampleframework
spring.cloud.nacos.config.server-addr: 127.0.0.1:8848
spring.cloud.nacos.discovery.server-addr: 127.0.0.1:8848

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  config:
    type: nacos
    nacos:
      namespace:
      #nacos的地址,可以更换为线上
      serverAddr: 127.0.0.1:8848
      #这里的名字就是registry.conf中 nacos的group名字
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      #nacos的地址,可以更换为线上
      server-addr: 127.0.0.1:8848
      #这里的名字就是registry.conf中 nacos的group名字
      group: SEATA_GROUP
      namespace:
      userName: "nacos"
      password: "nacos"
spring:
  cloud:
    nacos:
      config:
        file-extension: yaml
    alibaba:
      seata:
        tx-service-group: SEATA_GROUP